Repository icj4153/gitDocs, pull requests merged in 2022-12, with the labels that each got.

#12 Feature/about git GitHub
  Web/sub2-1.html
Labels: ✨ Feature

#14 feat: Add template
  Web/css/styles.css
  Web/sub5.html
Labels: ✨ Feature, 🔨 Refactor

#15 fix: css bug fix
  Web/css/styles.css
Labels: 🐞 BugFix

#16 feat : branch 설명추가
  Web/branch.png
  Web/sub3-1.html
  Web/sub3-2.html
Labels: ✨ Feature

#17 Feature/GitHub flow
  About-git.md
  README.md
  Web/assets/imgs/issue_1-1.png
  Web/assets/imgs/issue_1-2.png
  Web/assets/imgs/issue_2.png
  Web/assets/imgs/issue_3-1.png
  Web/assets/imgs/issue_3-2.png
  Web/assets/imgs/issue_3-3.png
  Web/assets/imgs/issue_closed.png
  Web/assets/imgs/issue_label_example_1.png
  Web/assets/imgs/issue_label_example_2.png
  Web/sub4.html
Labels: ✨ Feature

#18 feat: contribute page
  Web/assets/imgs/sub5/1-1.png
  Web/assets/imgs/sub5/1-2.png
  Web/assets/imgs/sub5/2-1.png
  Web/assets/imgs/sub5/2-2.png
  Web/assets/imgs/sub5/2-3.png
  Web/assets/imgs/sub5/3-1.png
  Web/assets/imgs/sub5/3-2.png
  Web/assets/imgs/sub5/4.png
  Web/assets/imgs/sub5/5-1.png
  Web/assets/imgs/sub5/5-2.png
  Web/assets/imgs/sub5/6.png
  Web/css/styles.css
  Web/sub5.html
Labels: ✨ Feature

#20 Feature/projectinfo
  Web/assets/imgs/br.png
  Web/assets/imgs/branch.png
  Web/assets/imgs/github_logo.png
  Web/assets/imgs/issue.png
  Web/assets/imgs/pr.png
  Web/assets/imgs/test1.png
  Web/assets/imgs/김동현.jpg
  Web/assets/imgs/김한나.jpg
  Web/assets/imgs/이다은.jpg
  Web/assets/imgs/임창준.jpg
  Web/index.html
  Web/sub3-2.html
Labels: ✨ Feature

#21 feat: Add Dockerfile
  Web/Dockerfile
Labels: ✨ Feature

#22 Feature/about git GitHub
  Web/sub2-1.html
  Web/sub2-2.html
Labels: ✨ Feature

#24 Develop
  Web/Dockerfile
  Web/assets/demo/chart-area-demo.js
  Web/assets/demo/chart-bar-demo.js
  Web/assets/demo/chart-pie-demo.js
  Web/assets/demo/datatables-demo.js
  Web/assets/imgs/br.png
  Web/assets/imgs/branch.png
  Web/assets/imgs/github_logo.png
  Web/assets/imgs/issue.png
  Web/assets/imgs/issue_1-1.png
  Web/assets/imgs/issue_1-2.png
  Web/assets/imgs/issue_2.png
  Web/assets/imgs/issue_3-1.png
  Web/assets/imgs/issue_3-2.png
  Web/assets/imgs/issue_3-3.png
  Web/assets/imgs/issue_closed.png
  Web/assets/imgs/issue_label_example_1.png
  Web/assets/imgs/issue_label_example_2.png
  Web/assets/imgs/pr.png
  Web/assets/imgs/sub5/1-1.png
  Web/assets/imgs/sub5/1-2.png
  Web/assets/imgs/sub5/2-1.png
  Web/assets/imgs/sub5/2-2.png
  Web/assets/imgs/sub5/2-3.png
  Web/assets/imgs/sub5/3-1.png
  Web/assets/imgs/sub5/3-2.png
  Web/assets/imgs/sub5/4.png
  Web/assets/imgs/sub5/5-1.png
  Web/assets/imgs/sub5/5-2.png
  Web/assets/imgs/sub5/6.png
  Web/assets/imgs/test1.png
  Web/assets/imgs/김동현.jpg
  Web/assets/imgs/김한나.jpg
  Web/assets/imgs/이다은.jpg
  Web/assets/imgs/임창준.jpg
  Web/css/styles.css
  Web/index.html
  Web/js/datatables-simple-demo.js
  Web/js/scripts.js
  Web/sub2-1.html
  Web/sub2-2.html
  Web/sub3-1.html
  Web/sub3-2.html
  Web/sub4-2.html
  Web/sub4.html
  Web/sub5.html
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css

#25 fix : navbar 내용 수정
  Web/index.html
  Web/sub2-1.html
  Web/sub2-2.html
  Web/sub3-1.html
  Web/sub3-2.html
  Web/sub4-2.html
  Web/sub4.html
  Web/sub5.html
Labels: Hotfix

#26 [Hotfix] layout 수정
  Web/sub2-1.html
  Web/sub2-2.html
  Web/sub3-1.html
  Web/sub3-2.html
  Web/sub4.html
Labels: 🔨 Refactor, 🎨 Html&css, Hotfix
